### ISSUE TITLE
New parents can select necessary needs to create a new event

### ISSUE THREAD

**Issue by meganft** [meganft/It-takes-a-village#2]
As a logged in new parent
When I go to my dashboard page 
I see an option to create a new event 
And I click on that link 
I go to the New Event Creation page (this is login page on slides)
I see a  list of categories of things I may need (Meals, Errands, Chores, Pampering, Visitors, Pet Care, and Babysitting) with a popup that hovers  with more information
I can select as many categories as I need
After I am done with this step ("submit" button of some sort)
I see the categories I selected with dropdown menu with more information about what I may need
I also see a place for notes or comments on each category
After I am done with this step (another "submit" button of some sort)
I then can drag each of the requests to the calendar and set a specific time
I can also duplicate an request from here (eg. laundry every week) without having to make a new selection from above.

**Comment by annadolan** [comment]
http://davidstutz.github.io/bootstrap-multiselect/
